[build]
  publish = "."

[[redirects]]
  from = "https://universalmusicdesign.org/"
  to = "https://www.confluencerecording.org/universalmusicdesign"
  status = 301
  force = true

[[redirects]]
  from = "https:www.//universalmusicdesign.org/"
  to = "https://www.confluencerecording.org/universalmusicdesign"
  status = 301
  force = true

[[redirects]]
  from = "http://.universalmusicdesign.org/"
  to = "https://www.confluencerecording.org/universalmusicdesign"
  status = 301
  force = true

[[redirects]]
  from = "http://www.universalmusicdesign.org/"
  to = "https://www.confluencerecording.org/universalmusicdesign"
  status = 301
  force = true